# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Z7M8C9A2' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  
  project '/Users/davidlopez/Documents/Github/-Z7M8C9A2/Z7M8C9A2/Z7M8C9A2.xcodeproj'
  
  use_frameworks!

  # Pods for PetcoAsistencias
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
  pod 'NVActivityIndicatorView'
  
end
