# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Z7M8C9A2' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'

  use_frameworks!

  # Pods for Z7M8C9A2

#  target 'Z7M8C9A2 WatchKit AppTests' do
#     inherit! :search_paths
    # Pods for testing

   end

#   target 'Z7M8C9A2 WatchKit AppUITests' do
    # Pods for testing
 #  end

 #  target 'Z7M8C9A2Tests' do
  #   inherit! :search_paths
    # Pods for testing
 #  end

#   target 'Z7M8C9A2UITests' do
    # Pods for testing
 #  end

# end

# target 'Z7M8C9A2 WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
 #  use_frameworks!

  # Pods for Z7M8C9A2 WatchKit App

#   target 'Z7M8C9A2 WatchKit AppTests' do
 #    inherit! :search_paths
    # Pods for testing
#   end

#   target 'Z7M8C9A2 WatchKit AppUITests' do
    # Pods for testing
 #  end

# end

# target 'Z7M8C9A2 WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Z7M8C9A2 WatchKit Extension

# end
